
paths:
  model: .results/model.pth
  optimizer: .results/optimizer.pth
  metrics: metrics.csv
  dataset: '../data/.files'

mlflow_url: "http://158.160.119.112:5000"

model:
  batch_size: 128
  n_epoch: 1
